### PR TITLE
change field-wrapper to v3 x-dynamic-component

### PR DESCRIPTION
**Pull request by wilfredchen**
Changed x-forms::field-wrapper to x-dynamic-component. php artisan view:cache throwing error.

### CODE REVIEW

**Review by awcodes — CHANGES_REQUESTED** [review]
These should follow the Filament blade views.

`<x-dynamic-component :component="$getFieldWrapperView()" :field="$field">`

**Review by awcodes — CHANGES_REQUESTED** [review]
You can actually drop everything except component and field. The field will handle all of the id, label, etc.

**Comment by awcodes** [comment]
Sorry to be nit picky. But if we're gonna do it let's do it right. 😃

**Comment by wilfredchen** [comment]
No worries!

**Review by awcodes — APPROVED** [review]

**Comment by awcodes** [comment]
Thanks.

**Pull request merged**
